### PR TITLE
Allow properties to be imported

### PR DESCRIPTION
**Pull request by upwebdesign**
@jnt0r Also allow for properties to be imported. I have found that in order to make API calls I need access tokens, this allows me to get access tokens. Let me know your thoughts.

### CODE REVIEW

**Comment by upwebdesign** [comment]
@jnt0r I apologize for reaching out about this PR, but it is something that I am needing for my project. If it makes sense, maybe I could be more than a contributor to help push these changes along? Appreciate your help with this!

**Comment by upwebdesign** [comment]
Closes #158

**Comment by jnt0r** [comment]
Sorry for the delay. Don't have much time this week. The feature is a good
idea. Could you just add the feature in the readme so it is documented?
Would be very nice. Then I we could release this feature.

Jesse Vista ***@***.***> schrieb am Di., 24. Aug. 2021, 16:29:

**Comment by upwebdesign** [comment]
@jnt0r added another commit to update the readme. Building and testing now. Do you think we can get this PR merged in today? I would very much like to use this feature as soon as possible.

**Comment by jnt0r** [comment]
Yes. looks good. I'm on the move at the moment. Will do it later today.

Jesse Vista ***@***.***> schrieb am Di., 24. Aug. 2021, 17:59:

**Comment by camiloiglesias96** [comment]
Hi! I having troubles to get the token from AuthenticationProperties calling the method getTokenSilently the console show me a error of undefined property 😢

**Pull request merged**
